pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r docs/widoco-docs/* public/
    - cp public/index-en.html public/index.html
    - mkdir -p public/ontospy
    - cp -r docs/ontospy-docs/* public/ontospy/
  artifacts:
    paths:
      - public
  only:
    - master
