pages:
  stage: deploy
  script:
    - mkdir -p public/rcao/docs/
    - cp -r docs/widoco-docs public/rcao/docs/
    - cp -r docs/ontospy-docs public/rcao/docs/
    - cp public/rcao/docs/widoco-docs/index-en.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
